### ISSUE TITLE
Sample log patterns

### ISSUE THREAD

**Issue by a7i** [grosser/logrecycler#4]
Currently, you can only preserve or discard logs. It would be nice to have a random sample in the event that you want to care about something but not every entry of it.

Something like:
```
- regex: 'Waited for .* due to client-side throttling'
  sample: 0.01 # keep 1% of it (can be random)
```

**Comment by grosser** [comment]
not a big fan of sampling logs, but it's a reasonable feature, I can add the feature, but would also be nice to have some fresh eyes on the codebase to see what's unintuitive
